name: CMake

on:
  push:
      branches: [ master ]
      paths:
        - 'src/*.cpp'
        - 'src/CMakeLists.txt'
        - 'include/*.h'
        - '*.cmake'
        - 'configs/*.cmake'
        - 'icon/*.cmake'
        - 'toolbar/*.cmake'
        - 'pics/*.cmake'
        - 'configs/*.kcfgc'
        - 'configs/*.kcfg'
        - 'CMakeLists.txt'
        - '.github/workflows/cmake.yml'
  pull_request:
      branches: [ master ]
      paths:
        - 'src/*.cpp'
        - 'include/*.h'
        - '*.cmake'
        - 'configs/*.cmake'
        - 'icon/*.cmake'
        - 'toolbar/*.cmake'
        - 'pics/*.cmake'
        - 'configs/*.kcfgc'
        - 'configs/*.kcfg'
        - 'CMakeLists.txt'
        - '.github/workflows/cmake.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: initialize
        uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt install --fix-missing -y gettext extra-cmake-modules pkg-config kdoctools-dev libkf5kio-dev libkf5widgetsaddons-dev libkf5coreaddons-dev libkf5config-dev libkf5xmlgui-dev libkf5declarative-dev libkf5completion-dev libkf5su-dev libkf5ldap-dev libkf5doctools-dev qt5-default
      - name: run cmake
        run: cmake .
      - name: run make
        run: make
