name: CMake

on:
  push:
      branches: [ master ]
      paths:
        - '*.cpp'
        - '*.h'
        - '*.cmake'
        - 'icon/*.cmake'
        - 'toolbar/*.cmake'
        - 'pics/*.cmake'
        - '*.kcfgc'
        - 'CMakeLists.txt'
        - '.github/workflows/cmake.yml'
  pull_request:
      branches: [ master ]
      paths:
        - '*.cpp'
        - '*.h'
        - '*.cmake'
        - 'icon/*.cmake'
        - 'toolbar/*.cmake'
        - 'pics/*.cmake'
        - 'CMakeLists.txt'
        - '.github/workflows/cmake.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: initialize
        uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt install -y gettext extra-cmake-modules pkg-config kdoctools-dev libkf5kio-dev libkf5widgetsaddons-dev libkf5coreaddons-dev libkf5config-dev libkf5xmlgui-dev libkf5declarative-dev libkf5completion-dev libkf5su-dev libkf5ldap-dev
      - name: run cmake
        run: cmake .
      - name: run make
        run: make
      
